Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "ControlServer"
  config.vm.network "private_network", ip: "192.168.10.11" 
  config.vm.provision  "shell", path: "provision.sh"
end
