Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
       
      #Setup for Web Server
      config.vm.define "web" do |web|
           web.vm.hostname = "web"
           web.vm.network "private_network", type: "dhcp"
           web.vm.network "forwarded_port", guest: 80, host: 8080
           web.vm.provision "puppet" do |puppet|
                  puppet.manifests_path = "manifests"
                  puppet.manifest_file = "default.pp"
       end
end
      # Setup of MYSQL DB Server
      config.vm.define "db" do |db|
            db.vm.hostname = "db"
            db.vm.network "private_network", type: "dhcp"
      end
end
