--- #Playbook to provision LAMP stack
- hosts: local
  sudo: yes
  gather_facts: no

  tasks:
    - name: Installing httpd on localhost
      yum: pkg=httpd state=installed
      notify: restart httpd
    - name: Install mariadb on localhost
      yum: pkg=mariadb state=installed
      notify: start mariadb
    - name: Placing default index file inside document root
      copy: src=index.html dest=/var/www/html/ mode=0644
      notify: restart httpd

  handlers:
    - name: restart httpd 
      service: name=httpd state=restarted enabled=yes
    - name: start mariadb
      service: name=mariadb state=started enabled=yes
